default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
  - repo: https://github.com/est31/cargo-udeps
    rev: v0.1.55
    hooks:
      - id: udeps
